skin    : "contrast"

# Site Author
author:
  name             : &name "Pedro Rodrigues"
  avatar           : "https://s3.wasabisys.com/psrandom/img/a/pedro-rodrigues-gray-bio.jpg"
  bio              : &description >-   
    DevOps, Full Stack Developer, Data Engineer and writer in spare time.
  location         : "Rio de Janeiro, RJ"
  email            : &email "pir.pedro@gmail.com"
  site             : &author_site "http://pirpedro.com.br"
  signature        : >-
              See you next time :sunglasses:
  links:
    home:  *author_site
    twitter: &twitter "pir_pedro"
    github: &github "pirpedro"
    facebook: &facebook "pirpedro"
    instagram: &instagram "pirpedro"
    linkedin: &linkedin "pirpedro"

  # tips service
  tip: 
    user: pirpedro
    description: Support me on Buy me a coffee!
    message: Thank you for visiting. You can now buy me a coffee!

# Site Settings
locale                   : "en-US"
title                    : &title "Pseudo Random"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : *title
description              : *description
url                      : &site "https://www.psrandom.com"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : psrandom/psrandom.github.io
cdn                      : https://s3.wasabisys.com/psrandom
teaser                   : "https://s3.wasabisys.com/psrandom/img/p/technology-teaser.jpeg"
logo                     : &logo "https://s3.wasabisys.com/psrandom/img/l/pseudorandom.png" # path of logo image to display in the masthead, e.g. "/assets/img/88x88.png"
masthead_title           : " " # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : true # true, false (default)
words_per_minute         : 200
darkmode                 : true
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : "pseudo-random"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : # true, false (default)
search_provider          : "algolia" # lunr (default), algolia, google
algolia:
  application_id         : "UMHS5VUWA5"
  index_name             : "PSEUDO_RANDOM"
  search_only_api_key    : "9c8f7e5a2856d98edf0df701f6578322"
  powered_by             : false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   : "A364EE89C5FE3F387B24DA9ECB635357"
yandex_site_verification :
naver_site_verification  : "f57e7c4c070de6199ff1e8a2fe8cc80d412adffb"

# Social Sharing
twitter:
  username               : *twitter
facebook:
  username               : *facebook 
  app_id                 : "261481851722479"
  publisher              :
og_image                 : *logo # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Person # Person or Organization (defaults to Person)
  name                   : *name # If the user or organization name differs from the site's name
  links: 
    - !Join [&twitter_url "https://twitter.com/", *twitter]
    - !Join [&facebook_url "https://www.facebook.com/", *facebook]
    - !Join [&instagram_url "https://instagram.com/", *instagram]
    - !Join [&linkedin_url "https://www.linkedin.com/in/", *linkedin]

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "custom"
  google: 
    tracking_id          : "UA-169340692-1"
    anonymize_ip         : false

    # Site Footer
footer:
  links:
    twitter: *twitter
    facebook: *facebook
    github: *github
    instagram: *instagram


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - script
  - private
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
    
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Sao_Paulo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-algolia
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      author_signature: true
      read_time: true
      comments: true
      share: true
      related: true
      head_scripts: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
      accept_tip: true
   # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"
  # _recipes
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: recipe
      author_profile: true
      author: Chef Pedro
      share: true
      comments: true
      head_stylesheets: "https://fonts.googleapis.com/css?family=Antic+Slab|Fira+Sans"
      classes: wide
      sidebar:
        position: right
      accept_tip: true
  # _projects
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: single
      author_profile: true
      author_signature: true
      share: true
      wide: true
      header:
        teaser: "https://s3.wasabisys.com/psrandom/img/p/projects-teaser.png"
      accept_tip: true

# remove the warning message in development deployment
github: [metadata]

